# Cloudflare Pages configuration
# See https://developers.cloudflare.com/pages/functions/wrangler-configuration/
name = "acars"
pages_build_output_dir = "apps/web/dist"
compatibility_date = "2026-03-12"
compatibility_flags = ["nodejs_compat", "enable_nodejs_http_modules"]
